stages:
  - PerformanceTest-Coordinadora

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: "fast"
  CACHE_COMPRESSION_LEVEL: "fast"

cache:
  paths:
    - .m2/repository

testPerformance:
  image: maven:latest
  stage: PerformanceTest-Coordinadora
  before_script:
    - mvn $MAVEN_CLI_OPTS clean compile
    - apt-get -y update

  script:
    - mvn clean test-compile gatling:test
  timeout: 3h 30m
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - when: always
  artifacts:
    when: always
    name: QA PERFORMANCE REPORT
    paths:
      - target/gatling
    expire_in: 1 week